### ISSUE TITLE
bug when plotting collapse maps

### ISSUE THREAD

**Issue by CatalinaYepes** [GEMScienceTools/rmtk#35]
When plotting the collapse map from the latest Virtual Machine the following error is appearing:

/usr/local/lib/python2.7/dist-packages/matplotlib/**init**.py in <module>()
    127     if not compare_versions(pyparsing.**version**, '1.5.6'):
    128         raise ImportError(
--> 129             "matplotlib requires pyparsing >= 1.5.6")
    130 
    131     # pyparsing 2.0.0 bug, but it may be patched in distributions

ImportError: matplotlib requires pyparsing >= 1.5.6

**Comment by raoanirudh** [comment]
@daniviga: It seems that the version of pyparsing installed in the VM is 1.5.2, which is incompatible with matplotlib. We should upgrade it unless there is a conflict with something else.

**Comment by daniviga** [comment]
Please use and test the new images based on Ubuntu 14.04: http://www.globalquakemodel.org/ova/master-u14.04/
The problem is that we are requiring a version of Matplotlib too new that requires `pyparsing >= 1.5.6` but updating it on the old VM will break compatibility with the stuff installed via `deb`

**Comment by raoanirudh** [comment]
Thank you Daniele.
